package search

type Site struct {
	Name         string
	URL          string
	Strategy     string
	BodyText     string
	RedirectLink string
	Priority     bool
}

var sites = []Site{
	{
		Name:     "9GAG",
		URL:      "https://9gag.com/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "About.me",
		URL:      "https://about.me/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Academia.edu",
		URL:      "https://independent.academia.edu/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "AngelList",
		URL:      "https://angel.co/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Aptoide",
		URL:      "https://%s.en.aptoide.com/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "AskFM",
		URL:      "https://ask.fm/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BLIP.fm",
		URL:      "https://blip.fm/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Badoo",
		URL:      "https://badoo.com/profile/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Bandcamp",
		URL:      "https://www.bandcamp.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Behance",
		URL:      "https://www.behance.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BitBucket",
		URL:      "https://bitbucket.org/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Blogger",
		URL:      "https://%s.blogspot.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BuzzFeed",
		URL:      "https://buzzfeed.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Canva",
		URL:      "https://www.canva.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "CashMe",
		URL:      "https://cash.me/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Cloob",
		URL:      "https://www.cloob.com/Name/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codecademy",
		URL:      "https://www.codecademy.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codechef",
		URL:      "https://www.codechef.com/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codementor",
		URL:      "https://www.codementor.io/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codepen",
		URL:      "https://codepen.io/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Coroflot",
		URL:      "https://www.coroflot.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Crevado",
		URL:      "https://%s.crevado.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Crunchyroll",
		URL:      "https://www.crunchyroll.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "DEV Community",
		URL:      "https://dev.to/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "DailyMotion",
		URL:      "https://www.dailymotion.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Designspiration",
		URL:      "https://www.designspiration.net/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "DeviantART",
		URL:      "https://%s.deviantart.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Discogs",
		URL:      "https://www.discogs.com/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Disqus",
		URL:      "https://disqus.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Docker Hub",
		URL:      "https://hub.docker.com/u/%s/",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Facebook",
		URL:      "https://www.facebook.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Fandom",
		URL:      "https://www.fandom.com/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Flickr",
		URL:      "https://www.flickr.com/people/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Flipboard",
		URL:      "https://flipboard.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Foursquare",
		URL:      "https://foursquare.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Giphy",
		URL:      "https://giphy.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "GitHub",
		URL:      "https://www.github.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Gitee",
		URL:      "https://gitee.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "GoodReads",
		URL:      "https://www.goodreads.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Gravatar",
		URL:      "http://en.gravatar.com/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "HubPages",
		URL:      "https://hubpages.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Imgur",
		URL:      "https://imgur.com/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Investing.com",
		URL:      "https://www.investing.com/traders/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Issuu",
		URL:      "https://issuu.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Itch.io",
		URL:      "https://%s.itch.io/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Jimdo",
		URL:      "https://%s.jimdosite.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Kaggle",
		URL:      "https://www.kaggle.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "KanoWorld",
		URL:      "https://api.kano.me/progress/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Keybase",
		URL:      "https://keybase.io/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Launchpad",
		URL:      "https://launchpad.net/~%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "LeetCode",
		URL:      "https://leetcode.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "LiveJournal",
		URL:      "https://%s.livejournal.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Mastodon",
		URL:      "https://mstdn.io/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Medium",
		URL:      "https://medium.com/@%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "MyAnimeList",
		URL:      "https://myanimelist.net/profile/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Myspace",
		URL:      "https://myspace.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Newgrounds",
		URL:      "https://%s.newgrounds.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "OK",
		URL:      "https://ok.ru/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Patreon",
		URL:      "https://www.patreon.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Photobucket",
		URL:      "https://photobucket.com/user/%s/library",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pinterest",
		URL:      "https://www.pinterest.com/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pixabay",
		URL:      "https://pixabay.com/en/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Plug.DJ",
		URL:      "https://plug.dj/@/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pokemon Showdown",
		URL:      "https://pokemonshowdown.com/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Rate Your Music",
		URL:      "https://rateyourmusic.com/~%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Reddit",
		URL:      "https://www.reddit.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Slack",
		URL:      "https://%s.slack.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "SlideShare",
		URL:      "https://slideshare.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Smashcast",
		URL:      "https://www.smashcast.tv/api/media/live/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "SoundCloud",
		URL:      "https://soundcloud.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "SourceForge",
		URL:      "https://sourceforge.net/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Spotify",
		URL:      "https://open.spotify.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Star Citizen",
		URL:      "https://robertsspaceindustries.com/citizens/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Taringa",
		URL:      "https://www.taringa.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "TradingView",
		URL:      "https://www.tradingview.com/u/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Trakt",
		URL:      "https://www.trakt.tv/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Twitch",
		URL:      "https://m.twitch.tv/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Unsplash",
		URL:      "https://unsplash.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "VK",
		URL:      "https://vk.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "VSCO",
		URL:      "https://vsco.co/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Venmo",
		URL:      "https://venmo.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Vimeo",
		URL:      "https://vimeo.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "WebNode",
		URL:      "https://%s.webnode.cz/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Wix",
		URL:      "https://%s.wix.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "YouPic",
		URL:      "https://youpic.com/photographer/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "boingboing.net",
		URL:      "https://bbs.boingboing.net/u/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "gfycat",
		URL:      "https://gfycat.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "last.fm",
		URL:      "https://last.fm/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "mixer.com",
		URL:      "https://mixer.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "osu!",
		URL:      "https://osu.ppy.sh/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Filmogs",
		URL:      "https://www.filmo.gs/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Trello",
		URL:      "https://trello.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Brew",
		URL:      "https://www.brew.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "NPM-Package",
		URL:      "https://www.npmjs.com/package/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "NPM",
		URL:      "https://www.npmjs.com/~%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Tumblr",
		URL:      "https://%s.tumblr.com/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "PlayStore",
		URL:      "https://play.google.com/store/apps/developer?id=%s",
		Strategy: "status",
		Priority: true,
	},
	// --- BODYTEXT SITES ---
	{
		Name:     "500px",
		URL:      "https://500px.com/%s",
		Strategy: "bodytext",
		BodyText: "Oops! This page doesn\u2019t exist.",
		Priority: false,
	},
	{
		Name:     "Basecamp",
		URL:      "https://%s.basecamphq.com",
		Strategy: "bodytext",
		BodyText: "The account you were looking for doesn't exist",
		Priority: false,
	},
	{
		Name:     "BitCoinForum",
		URL:      "https://bitcoinforum.com/profile/%s",
		BodyText: "The user whose profile you are trying to view does not exist.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Coderwall",
		URL:      "https://coderwall.com/%s",
		BodyText: "404! Our feels when that url is used",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Contently",
		URL:      "https://%s.contently.com/",
		BodyText: "We can't find that page!",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Dribbble",
		URL:      "https://dribbble.com/%s",
		BodyText: "Whoops, that page is gone.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Ebay",
		URL:      "https://www.ebay.com/usr/%s",
		BodyText: "The User ID you entered was not found",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Ello",
		URL:      "https://ello.co/%s",
		BodyText: "We couldn't find the page you're looking for",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "GitLab",
		URL:      "https://gitlab.com/api/v4/users?userName=%s",
		BodyText: "Page Not Found",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Gumroad",
		URL:      "https://www.gumroad.com/%s",
		BodyText: "Page not found.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "HackerNews",
		URL:      "https://news.ycombinator.com/user?id=%s",
		BodyText: "No such user.",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "HackerOne",
		URL:      "https://hackerone.com/%s",
		BodyText: "Page not found",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "HackerRank",
		URL:      "https://hackerrank.com/%s",
		BodyText: "Something went wrong",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "House-Mixes.com",
		URL:      "https://www.house-mixes.com/profile/%s",
		BodyText: "Profile Not Found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Houzz",
		URL:      "https://houzz.com/user/%s",
		BodyText: "The page you requested was not found.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "IFTTT",
		URL:      "https://www.ifttt.com/p/%s",
		BodyText: "The requested page or file does not exist",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Instagram",
		URL:      "https://www.instagram.com/%s",
		BodyText: "The link you followed may be broken",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Instructables",
		URL:      "https://www.instructables.com/member/%s",
		BodyText: "404: We're sorry, things break sometimes",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Kik",
		URL:      "https://ws2.kik.com/user/%s",
		BodyText: "The page you requested was not found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Kongregate",
		URL:      "https://www.kongregate.com/accounts/%s",
		BodyText: "Sorry, no account with that Name was found.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Letterboxd",
		URL:      "https://letterboxd.com/%s",
		BodyText: "Sorry, we can\u2019t find the page you\u2019ve requested.",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "MixCloud",
		URL:      "https://www.mixcloud.com/%s",
		BodyText: "Page Not Found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "NameMC (Minecraft.net skins",
		URL:      "https://Namemc.com/profile/%s",
		BodyText: "Profiles: 0 results",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Pexels",
		URL:      "https://www.pexels.com/@%s",
		BodyText: "Ouch, something went wrong!",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "ProductHunt",
		URL:      "https://www.producthunt.com/@%s",
		BodyText: "Product Hunt is a curation of the best new products",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Rajce.net",
		URL:      "https://%s.rajce.idnes.cz/",
		BodyText: "410",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Repl.it",
		URL:      "https://repl.it/@%s",
		BodyText: "404",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "ReverbNation",
		URL:      "https://www.reverbnation.com/%s",
		BodyText: "Sorry, we couldn't find that page",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Roblox",
		URL:      "https://www.roblox.com/user.aspx?userName=%s",
		BodyText: "Page cannot be found or no longer exists",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Scribd",
		URL:      "https://www.scribd.com/%s",
		BodyText: "Page not found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Signal",
		URL:      "https://community.signalusers.org/u/%s",
		BodyText: "Oops! That page doesn\u2019t exist or is private.",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Steam",
		URL:      "https://steamcommunity.com/id/%s",
		BodyText: "The specified profile could not be found",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "SteamGroup",
		URL:      "https://steamcommunity.com/groups/%s",
		BodyText: "No group could be retrieved for the given URL",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Telegram",
		URL:      "https://t.me/%s",
		BodyText: "<meta property=\"twitter:title\" content=\"Telegram: Contact",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Tinder",
		URL:      "https://www.gotinder.com/@%s",
		BodyText: "Looking for Someone?",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Trip",
		URL:      "https://www.trip.skyscanner.com/user/%s",
		BodyText: "Page not found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "TripAdvisor",
		URL:      "https://tripadvisor.com/members/%s",
		BodyText: "This page is on vacation\u2026",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Twitter",
		URL:      "https://www.twitter.com/%s",
		BodyText: "page doesn\u2019t exist",
		Priority: true,
	},
	{
		Name:     "Virgool",
		URL:      "https://virgool.io/@%s",
		BodyText: "۴۰۴",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "VirusTotal",
		URL:      "https://www.virustotal.com/ui/users/%s/trusted_users",
		BodyText: "not found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Wattpad",
		URL:      "https://www.wattpad.com/user/%s",
		BodyText: "userError-404",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "We Heart It",
		URL:      "https://weheartit.com/%s",
		BodyText: "Oops! You've landed on a moving target!",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "Wikipedia",
		URL:      "https://www.wikipedia.org/wiki/User:%s",
		BodyText: "If a page was recently created here, it may not be visible yet because of a delay in updating the database",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "YouNow",
		URL:      "https://api.younow.com/php/api/broadcast/info/user=%s/",
		BodyText: "No users found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "YouTube",
		URL:      "https://www.youtube.com/%s",
		BodyText: "Not Found",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "Cent",
		URL:      "https://beta.cent.co/@%s",
		BodyText: "<title>Cent</title>",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "BuyMeACoffee",
		URL:      "https://buymeacoff.ee/%s",
		BodyText: "It returned a 404 error",
		Strategy: "bodytext",
		Priority: false,
	},

	{
		Name:     "TikTok",
		URL:      "https://www.tiktok.com/@%s",
		BodyText: "Couldn&#x27;t find this account",
		Strategy: "bodytext",
		Priority: true,
	},
	{
		Name:     "OpenCollective",
		URL:      "https://opencollective.com/%s",
		BodyText: "Not found",
		Strategy: "bodytext",
		Priority: false,
	},
	{
		Name:     "PayPal",
		URL:      "https://www.paypal.me/%s",
		BodyText: "We can’t find a page with the URL you entered. Please try one of the links below or a search.",
		Strategy: "bodytext",
		Priority: true,
	},
}
