package search

type Site struct {
	Name         string
	URL          string
	Strategy     string
	BodyText     string
	RedirectLink string
	Priority     bool
}

var sites = []Site{
	{
		Name:     "9GAG",
		URL:      "https://9gag.com/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "About.me",
		URL:      "https://about.me/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Academia.edu",
		URL:      "https://independent.academia.edu/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "AngelList",
		URL:      "https://angel.co/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Aptoide",
		URL:      "https://%s.en.aptoide.com/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "AskFM",
		URL:      "https://ask.fm/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BLIP.fm",
		URL:      "https://blip.fm/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Badoo",
		URL:      "https://badoo.com/profile/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Bandcamp",
		URL:      "https://www.bandcamp.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Behance",
		URL:      "https://www.behance.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BitBucket",
		URL:      "https://bitbucket.org/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Blogger",
		URL:      "https://%s.blogspot.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "BuzzFeed",
		URL:      "https://buzzfeed.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Canva",
		URL:      "https://www.canva.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "CashMe",
		URL:      "https://cash.me/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Cloob",
		URL:      "https://www.cloob.com/Name/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codecademy",
		URL:      "https://www.codecademy.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codechef",
		URL:      "https://www.codechef.com/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codementor",
		URL:      "https://www.codementor.io/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Codepen",
		URL:      "https://codepen.io/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Coroflot",
		URL:      "https://www.coroflot.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Crevado",
		URL:      "https://%s.crevado.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Crunchyroll",
		URL:      "https://www.crunchyroll.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "DEV Community",
		URL:      "https://dev.to/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "DailyMotion",
		URL:      "https://www.dailymotion.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Designspiration",
		URL:      "https://www.designspiration.net/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "DeviantART",
		URL:      "https://%s.deviantart.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Discogs",
		URL:      "https://www.discogs.com/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Disqus",
		URL:      "https://disqus.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Docker Hub",
		URL:      "https://hub.docker.com/u/%s/",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Facebook",
		URL:      "https://www.facebook.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Fandom",
		URL:      "https://www.fandom.com/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Flickr",
		URL:      "https://www.flickr.com/people/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Flipboard",
		URL:      "https://flipboard.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Foursquare",
		URL:      "https://foursquare.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Giphy",
		URL:      "https://giphy.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "GitHub",
		URL:      "https://www.github.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Gitee",
		URL:      "https://gitee.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "GoodReads",
		URL:      "https://www.goodreads.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Gravatar",
		URL:      "http://en.gravatar.com/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "HubPages",
		URL:      "https://hubpages.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Imgur",
		URL:      "https://imgur.com/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Investing.com",
		URL:      "https://www.investing.com/traders/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Issuu",
		URL:      "https://issuu.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Itch.io",
		URL:      "https://%s.itch.io/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Jimdo",
		URL:      "https://%s.jimdosite.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Kaggle",
		URL:      "https://www.kaggle.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "KanoWorld",
		URL:      "https://api.kano.me/progress/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Keybase",
		URL:      "https://keybase.io/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Launchpad",
		URL:      "https://launchpad.net/~%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "LeetCode",
		URL:      "https://leetcode.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "LiveJournal",
		URL:      "https://%s.livejournal.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Mastodon",
		URL:      "https://mstdn.io/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Medium",
		URL:      "https://medium.com/@%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "MyAnimeList",
		URL:      "https://myanimelist.net/profile/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Myspace",
		URL:      "https://myspace.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Newgrounds",
		URL:      "https://%s.newgrounds.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "OK",
		URL:      "https://ok.ru/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Patreon",
		URL:      "https://www.patreon.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Photobucket",
		URL:      "https://photobucket.com/user/%s/library",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pinterest",
		URL:      "https://www.pinterest.com/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pixabay",
		URL:      "https://pixabay.com/en/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Plug.DJ",
		URL:      "https://plug.dj/@/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Pokemon Showdown",
		URL:      "https://pokemonshowdown.com/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Rate Your Music",
		URL:      "https://rateyourmusic.com/~%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Reddit",
		URL:      "https://www.reddit.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Slack",
		URL:      "https://%s.slack.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "SlideShare",
		URL:      "https://slideshare.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Smashcast",
		URL:      "https://www.smashcast.tv/api/media/live/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "SoundCloud",
		URL:      "https://soundcloud.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "SourceForge",
		URL:      "https://sourceforge.net/u/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Spotify",
		URL:      "https://open.spotify.com/user/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Star Citizen",
		URL:      "https://robertsspaceindustries.com/citizens/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Taringa",
		URL:      "https://www.taringa.net/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "TradingView",
		URL:      "https://www.tradingview.com/u/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Trakt",
		URL:      "https://www.trakt.tv/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Twitch",
		URL:      "https://m.twitch.tv/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Unsplash",
		URL:      "https://unsplash.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "VK",
		URL:      "https://vk.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "VSCO",
		URL:      "https://vsco.co/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Venmo",
		URL:      "https://venmo.com/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Vimeo",
		URL:      "https://vimeo.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "WebNode",
		URL:      "https://%s.webnode.cz/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Wix",
		URL:      "https://%s.wix.com",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "YouPic",
		URL:      "https://youpic.com/photographer/%s/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "boingboing.net",
		URL:      "https://bbs.boingboing.net/u/%s",
		Strategy: "status",
		Priority: false,
	}, {
		Name:     "gfycat",
		URL:      "https://gfycat.com/@%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "last.fm",
		URL:      "https://last.fm/user/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "mixer.com",
		URL:      "https://mixer.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "osu!",
		URL:      "https://osu.ppy.sh/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Filmogs",
		URL:      "https://www.filmo.gs/users/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Trello",
		URL:      "https://trello.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "Brew",
		URL:      "https://www.brew.com/%s",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "NPM-Package",
		URL:      "https://www.npmjs.com/package/%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "NPM",
		URL:      "https://www.npmjs.com/~%s",
		Strategy: "status",
		Priority: true,
	},
	{
		Name:     "Tumblr",
		URL:      "https://%s.tumblr.com/",
		Strategy: "status",
		Priority: false,
	},
	{
		Name:     "PlayStore",
		URL:      "https://play.google.com/store/apps/developer?id=%s",
		Strategy: "status",
		Priority: true,
	},
}
